name=7Semi BMI323
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=Lightweight and efficient BMI323 IMU sensor library.
paragraph=Provides a clean and high-performance interface for Bosch BMI323 6-axis IMU over I2C and SPI. Supports accelerometer and gyroscope configuration, FIFO, interrupts, calibration, and sensor data processing. Designed for embedded efficiency and ease of use.
category=Sensors
url=https://github.com/7semi-solutions/7Semi-BMI323
includes=7Semi_BMI323.h



